### ISSUE TITLE
-T ption with list of suspected dns

### ISSUE THREAD

**Issue by xsallowed** [jonschipp/mal-dnssearch#11]
hi
I am trying to us following command to test couple of URLs in a text file:

mal-dnssearch -f dns /home/analyst/Desktop/test.txt -T dns

I am getting an error saying "unkown type" 

Can anyone help me here?

My file looks like 

test.txt
www.google.com
www.badguysdomain.com

Regards

**Comment by clinttepe** [comment]
There is no "dns" option for Type; I believe this is the command you want:
`mal-dnssearch -f /home/analyst/Desktop/test.txt -T custom-dns`

Thanks for providing your test file examples, that makes it easier to help!
